---
title: "Input data sets for R"
author: "Steve Simon"
date: "December 28, 2020"
output: html_document
---

This program reads a variety of different text files and produces binary files in R format.

```{r setup}
suppressMessages(suppressWarnings(library(magrittr)))
suppressMessages(suppressWarnings(library(readr)))
suppressMessages(suppressWarnings(library(stringr)))
```

```{r fly1}
text_name <- "sa2020-d-fly1.txt"
bin_name  <- str_replace(text_name, "txt", "Rdata")
fly1 <- data.frame(read_table2(text_name, col_names=FALSE))
names(fly1) <- "day"
save(fly1, file=bin_name)
rm(list="fly1")
load(file=bin_name)
head(fly1)
```

```{r fly2}
text_name <- "sa2020-d-fly2.txt"
bin_name  <- str_replace(text_name, "txt", "Rdata")
fly2 <- data.frame(read_table2(text_name, col_names=FALSE))
names(fly2) <- c("day", "cens")
save(fly2, file=bin_name)
rm(list="fly2")
load(file=bin_name)
head(fly2)
```

```{r fly3}
text_name <- "sa2020-d-fly3.txt"
bin_name  <- str_replace(text_name, "txt", "Rdata")
fly3 <- data.frame(read_table2(text_name, col_names=FALSE))
names(fly3) <- c("day", "cens")
save(fly3, file=bin_name)
rm(list="fly3")
load(file=bin_name)
head(fly3)
```

```{r rats}
text_name <- "sa2020-d-rats.csv"
bin_name  <- str_replace(text_name, "txt", "Rdata")
rats <- data.frame(read_csv(text_name, col_names=TRUE))
save(rats, file=bin_name)
rm(list="rats")
load(file=bin_name)
head(rats)
```
